CREATE TABLE NATURAL_RESOURCE_DIST (
    NATURAL_RESOURCE_DIST_CODE varchar(5)  NOT NULL,
    DESCRIPTION varchar(100)  NOT NULL,
    EMAIL_ADDRESS varchar(100)  NOT NULL,
    EFFECTIVE_DATE date NOT NULL,
    EXPIRY_DATE date NULL,
    CONSTRAINT NATURAL_RESOURCE_DIST_pk PRIMARY KEY (NATURAL_RESOURCE_DIST_CODE)
);

INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DMH', '100 Mile House Natural Resource District', 'FLNR.100MileHouseDistrict@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DCR', 'Campbell River Natural Resource District', 'FTA.DCR@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DCC', 'Cariboo-Chilcotin Natural Resource District', 'DCC.Tenures@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DCS', 'Cascades Natural Resource District', 'Forests.CascadesDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DCK', 'Chilliwack Natural Resource District', 'FTA.DCKDSQ@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DKM', 'Coast Mountains Natural Resource District', 'DCM.Tenures@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DFN', 'Fort Nelson Natural Resource District', 'Forests.FortNelsonDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DQC', 'Haida Gwaii Natural Resource District', 'FrontCounterHaidaGwaii@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DMK', 'Mackenzie Natural Resource District', 'Forests.MackenzieDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DND', 'Nadina Natural Resource District', 'Forests.NadinaDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DNI', 'North Island - Central Coast Natural Resource District', 'FTA.DIC@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DOS', 'Okanagan Shuswap Natural Resource District', 'DOS.CPRP@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DPC', 'Peace Natural Resource District', 'PeaceDistrict.Tenures@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DPG', 'Prince George Natural Resource District', 'Forests.PrinceGeorgeDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DQU', 'Quesnel Natural Resource District', 'Forests.QuesnelDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DRM', 'Rocky Mountain Natural Resource District', 'FORESTS.rockymountaindistrictoffice@gov.bc.ca ', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DSQ', 'Sea to Sky Natural Resource District', 'FTA.DCKDSQ@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DSE', 'Selkirk Natural Resource District', 'Resources.Nelson@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DSS', 'Skeena Stikine Natural Resource District', 'Forests.SkeenaStikineDistrictOffice@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DSI', 'South Island Natural Resource District', 'FTA.DSI@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DVA', 'Stuart Nechako Natural Resource District', 'dsn.submissions@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DSC', 'Sunshine Coast Natural Resource District', 'FTA.DSC@gov.bc.ca', CURRENT_TIMESTAMP);
INSERT INTO NATURAL_RESOURCE_DIST (NATURAL_RESOURCE_DIST_CODE, DESCRIPTION, EMAIL_ADDRESS, EFFECTIVE_DATE) VALUES ('DKA', 'Thompson Rivers Natural Resource District', 'DTR.Tenures@gov.bc.ca', CURRENT_TIMESTAMP);

