name: API Validation Check

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  verify-api:
    name: Verify API Health
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [ test, prod ]
    env:
      OS_DOMAIN: apps.silver.devops.gov.bc.ca
    steps:
      - uses: actions/checkout@v4

      - name: Check Health on ${{ matrix.package }} environment
        uses: matt-ball/newman-action@master
        with:
          collection: postman/OG.postman_collection.json
          envVar: '[{"key":"URL_OG","value":"https://${{ github.event.repository.name }}-${{ matrix.package }}-backend.${{ env.OS_DOMAIN }}"}]'
          reporters: '["cli"]'
          folder: '["general"]'
          